#ifndef INCLUDE_GITXX_ERROR_HPP_
#define INCLUDE_GITXX_ERROR_HPP_

#include <cstdint>
#include <string>
#include <system_error>
#include <type_traits>

enum class GitErrc : std::uint8_t {
  /// @brief Requested object could not be found.
  not_found = 3,
  /// @brief Object exists preventing operation.
  exists = 4,
  /// @brief More than one object matches.
  ambiguous = 5,
  /// @brief Output buffer too short to hold data.
  bufs = 6,
  /// @brief This is a special error that is never generated by libgit.
  /// You can return it from a callback (e.g to stop an iteration) to know
  /// that it was generated by the callback and not by libgit.
  user = 7,
  /// @brief Operation not allowed on bare repository.
  bare_repo = 8,
  /// @brief HEAD refers to branch with no commits.
  unborn_branch = 9,
  /// @brief Merge in progress prevented operation
  unmerged = 10,
  /// @brief Reference was not fast-forwardable
  non_fast_forward = 11,
  /// @brief Name/ref spec was not in a valid format
  invalid_spec = 12,
  /// @brief Checkout conflicts prevented operation
  conflict = 13,
  /// @brief Lock file prevented operation
  locked = 14,
  /// @brief Reference value does not match expected
  modified = 15,
  /// @brief Authentication error
  auth = 16,
  /// @brief Server certificate is invalid
  certificate = 17,
  /// @brief Patch/merge has already been applied
  applied = 18,
  /// @brief The requested peel operation is not possible
  peel = 19,
  /// @brief Unexpected EOF
  eof = 20,
  /// @brief Invalid operation or input
  invalid = 21,
  /// @brief Uncommitted changes in index prevented operation
  uncommitted = 22,
  /// @brief The operation is not valid for a directory
  directory = 23,
  /// @brief A merge conflict exists and cannot continue
  merge_conflict = 24,
  /// @brief A user-configured callback refused to act
  passthrough = 30,
  /// @brief Signals end of iteration with iterator
  iterover = 31,
  /// @brief Internal only
  retry = 32,
  /// @brief Hashsum mismatch in object
  mismatch = 33,
  /// @brief Unsaved changes in the index would be overwritten
  index_dirty = 34,
  /// @brief Patch application failed
  apply_fail = 35,
  /// @brief The object is not owned by the current user
  owner = 36,
  /// @brief The operation timed out
  timeout = 37,
  /// @brief There were no changes
  unchanged = 38,
  /// @brief An option is not supported
  not_supported = 39,
  /// @brief The subject is read-only
  readonly = 40,
};

/// @brief gitxx error category.
struct GitErrcCategory : std::error_category {
  /// @brief Gives the name of the error.
  [[nodiscard]] const char* name() const noexcept override;

  /// @brief Gives the description of the error.
  [[nodiscard]] std::string message(int error_code) const override;
};

namespace std {

template <>
struct is_error_code_enum<GitErrc> : std::true_type {};

}  // namespace std

std::error_code make_error_code(GitErrc);

const GitErrcCategory gitErrcCategory{};

#endif  // INCLUDE_GITXX_ERROR_HPP_
