#include <converters/error.hpp>
#include <gitxx/error.hpp>
#include <string>
#include <system_error>

const char* GitErrcCategory::name() const noexcept { return "Git error code"; }

std::string GitErrcCategory::message(int error_code) const {
  switch (error_code) {
    default:
      return "Git error code";
    case static_cast<int>(GitErrc::not_found):
      return "Requested object could not be found.";
    case static_cast<int>(GitErrc::exists):
      return "Object exists preventing operation.";
    case static_cast<int>(GitErrc::ambiguous):
      return "More than one object matches.";
    case static_cast<int>(GitErrc::bufs):
      return "Output buffer too short to hold data.";
    case static_cast<int>(GitErrc::user):
      return "This is a special error that is never generated by libgit2 "
             "code. You can return it from a callback (e.g to stop an "
             "iteration) to know that it was generated by the callback and "
             "not by libgit2.";
    case static_cast<int>(GitErrc::bare_repo):
      return "Operation not allowed on bare repository.";
    case static_cast<int>(GitErrc::unborn_branch):
      return "HEAD refers to branch with no commits.";
    case static_cast<int>(GitErrc::unmerged):
      return "Merge in progress prevented operation";
    case static_cast<int>(GitErrc::non_fast_forward):
      return "Reference was not fast-forwardable";
    case static_cast<int>(GitErrc::invalid_spec):
      return "Name/ref spec was not in a valid format";
    case static_cast<int>(GitErrc::conflict):
      return "Checkout conflicts prevented operation";
    case static_cast<int>(GitErrc::locked):
      return "Lock file prevented operation";
    case static_cast<int>(GitErrc::modified):
      return "Reference value does not match expected";
    case static_cast<int>(GitErrc::auth):
      return "Authentication error";
    case static_cast<int>(GitErrc::certificate):
      return "Server certificate is invalid";
    case static_cast<int>(GitErrc::applied):
      return "Patch/merge has already been applied";
    case static_cast<int>(GitErrc::peel):
      return "The requested peel operation is not possible";
    case static_cast<int>(GitErrc::eof):
      return "Unexpected EOF";
    case static_cast<int>(GitErrc::invalid):
      return "Invalid operation or input";
    case static_cast<int>(GitErrc::uncommitted):
      return "Uncommitted changes in index prevented operation";
    case static_cast<int>(GitErrc::directory):
      return "The operation is not valid for a directory";
    case static_cast<int>(GitErrc::merge_conflict):
      return "A merge conflict exists and cannot continue";
    case static_cast<int>(GitErrc::passthrough):
      return "A user-configured callback refused to act";
    case static_cast<int>(GitErrc::iterover):
      return "Signals end of iteration with iterator";
    case static_cast<int>(GitErrc::retry):
      return "Internal only";
    case static_cast<int>(GitErrc::mismatch):
      return "Hashsum mismatch in object";
    case static_cast<int>(GitErrc::index_dirty):
      return "Unsaved changes in the index would be overwritten";
    case static_cast<int>(GitErrc::apply_fail):
      return "Patch application failed";
    case static_cast<int>(GitErrc::owner):
      return "The object is not owned by the current user";
    case static_cast<int>(GitErrc::timeout):
      return "The operation timed out";
    case static_cast<int>(GitErrc::unchanged):
      return "There were no changes";
    case static_cast<int>(GitErrc::not_supported):
      return "An option is not supported";
    case static_cast<int>(GitErrc::readonly):
      return "The subject is read-only";
  }
}

std::error_code make_error_code(GitErrc error) {
  return {static_cast<int>(error), gitErrcCategory};
}

std::format_context::iterator std::formatter<GitErrc>::format(
    GitErrc errc, std::format_context& ctx) const {
  return std::formatter<std::string>::format(
      make_error_code(errc).message(), ctx);
}
