name: Clang-Tidy

on:
  push:
    paths:
      - "src/**"
      - "include/**"
      - "tests/**"
      - ".clang-tidy"
      - ".github/workflows/clang-tidy.yaml"
  pull_request:
    paths:
      - "src/**"
      - "include/**"
      - "tests/**"
      - ".clang-tidy"
      - ".github/workflows/clang-tidy.yaml"

jobs:
  clang-tidy:
    name: Run clang-tidy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy ninja-build

      - name: Cache FetchContent dependencies
        uses: actions/cache@v5
        with:
          path: build/release/_deps
          key: Linux-fetchcontent-libgit2-v1.9.1

      - name: Configure CMake
        run: cmake --preset release

      - name: Run clang-tidy
        run: |
          find src include tests -type f \( -name "*.cpp" -o -name "*.cc" -o -name "*.cxx" -o -name "*.c" \) -print0 | \
          xargs -0 -P$(nproc) clang-tidy -p build/release --config-file=.clang-tidy
