name: Tests

on:
  - push
  - pull_request

env:
  BUILD_DIR: build

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        brew install cmake libgit2
        rm /opt/homebrew/include/git2/stdint.h
    - name: CMake Configure
      run: |
        cmake -S . -B ${{env.BUILD_DIR}}
    - name: CMake Build
      run: |
        cmake --build ${{env.BUILD_DIR}}
    - name: test
      run: |
        cd ${{env.BUILD_DIR}} && ctest
