---
name: "Tests"

on:
  - push
  - pull_request

env:
  BUILD_DIR: build

jobs:
  build-macos:
    name: "MacOS Build"
    runs-on: macos-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Install dependencies"
        run: |
          brew install libgit2 googletest
      - name: "CMake configure"
        run: |
          cmake -S . -B ${{env.BUILD_DIR}}
      - name: "CMake build"
        run: |
          cmake --build ${{env.BUILD_DIR}}
      - name: Run clang-tidy
        uses: HorstBaerbel/action-clang-tidy@1.2
        # These are optional (defaults displayed)
        with:
          scandir: '.'
          builddir: ${{env.BUILD_DIR}}
          excludedirs: ''
          extensions: 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'
          cmakeoptions: ''
      - name: "Tar files"
        run: tar -czf build-macos-aarch64.tar.gz "${{env.BUILD_DIR}}"
      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: build-macos-aarch64
          path: build-macos-aarch64.tar.gz
  # test-macos:
    # name: "MacOS Test"
    # needs: build-macos
    # runs-on: macos-latest
    # steps:
      # - name: "Download build artifact"
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: build-macos-aarch64
      #     path: artifacts
      # - name: "Untar files"
      #   run: |
      #     tar -xvf artifacts/build-macos-aarch64.tar.gz
      - name: "Test"
        run: |
          cd ${{env.BUILD_DIR}} && ctest
      - name: "Upload results"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: macos-aarch64-test-results
          path: "${{env.BUILD_DIR}}/Testing"
