name: Tests

on:
  - push
  - pull_request

env:
  BUILD_DIR: build

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        brew update
        brew install cmake libgit2@1.9.0
    - name: Make libgit2 work
      run: |
        # rm /opt/homebrew/include/git2/stdint.h
        patch -u /opt/homebrew/Cellar/libgit2/1.9.0/lib/cmake/libgit2/libgit2Targets.cmake .github/libgit2_190.patch
    - name: CMake Configure
      run: |
        cmake -S . -B ${{env.BUILD_DIR}}
    - name: CMake Build
      run: |
        cmake --build ${{env.BUILD_DIR}}
    - name: test
      run: |
        cd ${{env.BUILD_DIR}} && ctest
